Repository fga-eps-mds/2021-1-Bot, pull requests merged in 2021-08, with the labels that each got.

#24 Merge de branch
  docs/templete.md
Labels: documentation, Time-Capivara

#69 Documentation/#40/definicao das epics plus ultra
  docs/documento-das-features.md
Labels: documentation, Time-PlusUltra

#84 Modificando o Rasa com o douglas
  docs/tutoriais/Tutorial_edicao_Rasa.md
Labels: documentation
