Repository fga-eps-mds/2021-1-Bot, pull requests merged in 2021-10, with the labels that each got.

#249 Inicio da nova versão do backlog
  docs/Versão2-Backlog.md
Labels: documentation, Time-PlusUltra, Time-Capivara, Time-Slowbros

#273 Feature#271/teste rasa
  .gitignore
  Makefile
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
  bot/tests/test_stories.yml
  docs/img/intent_confusion_matrix.png
  docs/img/intent_confusion_matrix_example.png
  docs/img/intent_histogram.png
  docs/img/intent_histogram_example.png
  docs/img/story_confusion_matrix.png
  docs/tutoriais/Tutorial_rasa_testes.md
Labels: Time-PlusUltra, Tecnologista, development

#283 Feature#217/arquivos csv com python nas actions
  .gitignore
  actions/actions.py
  actions/requirements.txt
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-PlusUltra, devops, Tecnologista
