Repository fga-eps-mds/2021-1-Bot, pull requests merged in 2021-09, with the labels that each got.

#131 🆒(#128): Treinando o bot para responder se ele é um bot
  bot/data/nlu.yml
  bot/domain.yml
Labels: Time-PlusUltra, Tecnologista

#135 🔁(#114): Adicionando aos tutoriais o treinamento rasa com telegram
  docs/tutoriais/Tutorial_Integracao_Rasa_com_Telegram.md
Labels: Time-PlusUltra, Tecnologista

#148 :bug:(#132): correcao dos links de como contribuir
  README.md
Labels: bug

#156 💡(#155): Implementando o fallback do bot
  bot/data/nlu.yml
  bot/data/rules.yml
  bot/domain.yml
Labels: Time-PlusUltra, Tecnologista

#145 :pencil: [#103] Canvas
  docs/canvas.md
Labels: documentation, Time-PlusUltra, Time-Capivara

#153 Feature#141/rasa deploy
  Dockerfile
  bot/credentials.yml
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
  docker/bot.Dockerfile
  docs/tutoriais/Deploy_no_Heroku.md
  heroku.yml
  start_services.sh
Labels: Time-PlusUltra

#160 Documentation#159/alteracao politica
  docs/politicas/branches.md
Labels: documentation, Time-PlusUltra, Time-Capivara, Time-Slowbros

#157 📝(#143): Adicionando o Plano de Comunicação
  docs/plano-de-comunicacao.md
Labels: documentation

#170 :pencil: (#55) : introdução
  docs/IdentidadeVisual.md
Labels: documentation

#175 🐛(#174): Resolvendo o erro em make build
  .example.env
  docker-compose.yml
  docker/bot.Dockerfile
Labels: Time-PlusUltra, devops, Tecnologista

#171 📝(#52): documentação sprint 3
  gerencia/TimeCapivara/sprint3/results.md
Labels: documentation, Time-Capivara

#164 Improvement#99/folha de estilo
  Makefile
  actions/.pep8
  actions/actions.py
  actions/requirements.txt
  bot/requirements.txt
  docker/actions.Dockerfile
  docker/bot.Dockerfile
  docs/folha-de-estilo.md
Labels: documentation, Time-PlusUltra, Time-Capivara, Time-Slowbros, devops

#172 Documentation#154/roadmap
  docs/roadmap.md
Labels: documentation, Time-PlusUltra, Time-Capivara, product owner, Time-Slowbros

#122 Documento de visao
  docs/CODE_OF_CONDUCT.md
  docs/IdentidadeVisual.md
  docs/PersonalidadeDoBot.md
  docs/Termo-de-Abertura-do-Projeto.md
  docs/documento-de-visao.md
  docs/plano-de-comunicacao.md
Labels: documentation, product owner

#186 Feature#162/transmissao e prevencao
  bot/credentials.yml
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-PlusUltra, Time-Capivara, Time-Slowbros, Tecnologista

#195 Feature#169/regras para lugares especificos
  bot/credentials.yml
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-PlusUltra, Time-Capivara, Time-Slowbros, Tecnologista

#187 Documentation#165/gerencia sprint5
  gerencia/TimeCapivara/sprint4/planejamento.md
  gerencia/TimeCapivara/sprint4/resultados.md
  gerencia/TimeCapivara/sprint5/planejamento.md
  gerencia/TimeCapivara/sprint5/resultados.md
Labels: documentation

#203 Documentation#166/gerencia sprint6
  gerencia/TimeCapivara/sprint6/planejamento.md
  gerencia/TimeCapivara/sprint6/resultados.md
Labels: documentation

#210 Hotfix#209/graficos velocity burndown
  gerencia/TimeCapivara/assets/burndown_sprint0.png
  gerencia/TimeCapivara/assets/burndown_sprint1.png
  gerencia/TimeCapivara/assets/burndown_sprint2.png
  gerencia/TimeCapivara/assets/burndown_sprint3.png
  gerencia/TimeCapivara/assets/burndown_sprint4.jpg
  gerencia/TimeCapivara/assets/burndown_sprint5.jpg
  gerencia/TimeCapivara/assets/burndown_sprint6.jpg
  gerencia/TimeCapivara/assets/velocity_sprint0.png
  gerencia/TimeCapivara/assets/velocity_sprint1.png
  gerencia/TimeCapivara/assets/velocity_sprint2.png
  gerencia/TimeCapivara/assets/velocity_sprint3.png
  gerencia/TimeCapivara/assets/velocity_sprint4.jpg
  gerencia/TimeCapivara/assets/velocity_sprint5.jpg
  gerencia/TimeCapivara/assets/velocity_sprint6.jpg
Labels: bug, documentation

#199 Documentation#182/correção documento de arquitetura
  docs/documento-de-arquitetura.md
Labels: documentation, Architecture

#212 🔁(#211): link quebrado corrigido
  README.md
Labels: bug, documentation, Time-Capivara

#225 :pencil:(#224): linkado o video de instalação de Docker e WSL para Windows 10
  README.md
Labels: documentation, Time-PlusUltra

#221 :pencil:(#218): Adicionado documento de FAQ
  docs/2021-09-16-faq.md
Labels: documentation, Time-PlusUltra

#226 :repeat:(#219): Adicionando informacoes no template para otimizar os PR's
  .github/pull_request_template.md
Labels: documentation, Time-PlusUltra

#235 :pencil:(#234): atualizado roadmap de devops
  docs/documento-de-devops.md
Labels: documentation, Time-PlusUltra, devops

#241 :pencil:(#233): Adicionado versão inicial do documento que explica como subir o container da documentação
  docs/2021-09-21-dev-docs.md
Labels: documentation, Time-PlusUltra, devops

#240 Documentation#228/update doc de arquitetura
  docs/documento-de-arquitetura.md
Labels: documentation, Time-PlusUltra, Time-Capivara, Time-Slowbros, Architecture

#231 🔁(#215): mudança nas orientações para issues
  docs/CONTRIBUTING.md
Labels: bug, documentation, Time-Capivara

#248 Documentation#245/fluxo de trabalho
  docs/fluxo-de-trabalho.md
Labels: documentation, Time-PlusUltra

#246 :pencil:(#243): Adicionando documentacao das sprints 8 e 9
  gerencia/EquipePlusUltra/sprint8_pu/2021-09-16-planejamento_sprint8.md
  gerencia/EquipePlusUltra/sprint8_pu/2021-09-24-resultados_sprint8.md
  gerencia/EquipePlusUltra/sprint9_pu/2021-09-24-planejamento_sprint9.md
  gerencia/EquipePlusUltra/sprint9_pu/2021-09-24-resultados_sprint9.md
Labels: documentation, Time-PlusUltra

#238 Documentation#223/gerencia capivaras sprint7
  gerencia/TimeCapivara/assets/burndown_sprint7.png
  gerencia/TimeCapivara/assets/conhecimento_sprint7.png
  gerencia/TimeCapivara/assets/velocity_sprint7.png
  gerencia/TimeCapivara/sprint7/planejamento.md
  gerencia/TimeCapivara/sprint7/resultados.md
Labels: documentation, Time-Capivara

#253 :pencil:(#252): adicionado link no README para para a seção da FAQ sobre variáveis ambiente
  README.md
  docs/2021-09-16-faq.md
Labels: documentation

#251 Documentação sprints slowbros
  gerencia/GrupoSlowbros/sprint7sb/planejamento-sprint7.md
  gerencia/GrupoSlowbros/sprint7sb/resultado-sprint7.md
  gerencia/GrupoSlowbros/sprint8sb/planejamento-sprint8.md
  gerencia/GrupoSlowbros/sprint8sb/resultado-sprint8.md
Labels: documentation, Time-Slowbros

#259 Adição dos vídeos da R1 e inclusão de badges
  README.md
Labels: documentation

#255 Feature(#247)/us26
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-Capivara, development

#267 :bulb:(#257): implementada a US29
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-PlusUltra, development

#261 Feature #260/US11
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-Slowbros, development

#263 Feature #262/US12
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-Slowbros, development

#266 Feature #264/US25
  bot/data/nlu.yml
  bot/data/stories.yml
  bot/domain.yml
Labels: Time-Slowbros, development
